//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoologico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animales()
        {
            this.Citas = new HashSet<Citas>();
        }
    
        public string Id_Animal { get; set; }
        public string Nombre_Animal { get; set; }
        public string Especie_Animal { get; set; }
        public string Categoria_Animal { get; set; }
        public string Id_Zona { get; set; }
        public Nullable<int> Edad_Animal { get; set; }
        public string Descripcion_Animal { get; set; }
        public string Nombre_Cientifico_Animal { get; set; }
        public string Tiempo_Zoologico { get; set; }
    
        public virtual Zonas Zonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
    }
}
