//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoologico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public string Numero_Compra { get; set; }
        public Nullable<System.DateTime> Fecha_Compra { get; set; }
        public string Cantidad_Compra { get; set; }
        public string Valor_Compra { get; set; }
        public string Id_Plan { get; set; }
        public string Cedula_Cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Planes Planes { get; set; }
    }
}
