//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoologico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tiquete
    {
        public string Numero_Tiquete { get; set; }
        public Nullable<System.DateTime> Hora_Ingreso_Tiquete { get; set; }
        public Nullable<System.DateTime> Hora_salida_Tiquete { get; set; }
        public string Valor_Hora_Tiquete { get; set; }
        public string Id_Parqueadero { get; set; }
        public string Placa_Vehiculo { get; set; }
    
        public virtual Parqueadero Parqueadero { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
